name: Django CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.7, 3.8, 3.9]

    steps:
    - uses: actions/checkout@v3
    - name: Run a one-line script
      run: echo Hello, world!
      
    - name: run a multi-level script
      run: |
        echo Add oyher action th build,
        echo test and deploy your project!
